In [1]:
import numpy as np

In [10]:
with np.load('data/irl/extrinseques.npz') as data:
    print(data.files)
    print(data['KR'])
    print(data['distR'])
    print(data['rvecsR'])
    print(data['tvecsR'])

['KR', 'distR', 'rvecsR', 'tvecsR']
[[6.34140430e+03 0.00000000e+00 1.51148593e+03]
 [0.00000000e+00 6.26725586e+03 9.90294552e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]
[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]
